### ISSUE TITLE
Don't push .env file

### ISSUE THREAD

**Issue by raideno** [LynixDancho/Telegram-Solana-bot#1]
The `.env` file contains the bot token, and I just used it to log in to your Telegram bot and send messages to a bunch of people with it.

Add the file to the `.gitignore` so it won’t be pushed to the repository.

**Comment by raideno** [comment]
generate an appropriate `.gitignore` file using this [website](https://www.toptal.com/developers/gitignore) and the keywords: `rust`, `dotenv`.

`.gitignore`
```txt
# Created by https://www.toptal.com/developers/gitignore/api/rust,dotenv
# Edit at https://www.toptal.com/developers/gitignore?templates=rust,dotenv

### dotenv ###
.env

### Rust ###
# Generated by Cargo
# will have compiled files and executables
debug/
target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these, which store debugging information
*.pdb

# End of https://www.toptal.com/developers/gitignore/api/rust,dotenv
```

**Comment by LynixDancho** [comment]
Dear kichou Nadir ,
i received your letter and i'm thankful for your remarks And i would like
to reassure you that i really don't care about that Rust project it was
just a test for the language to see if its Good for Making Telegram Bots
And i am currently working on another bot project and i made sure to not
Push the Env File , however i do thank you for your concerns it means alot
to me , And please open a Discord i just found this
Message by mistake not gonna Lie
I hope u fortune and good luck in ur next projects

yours truly LynixDancho
